### ISSUE TITLE
Please add ACT-W National Conference

### ISSUE THREAD

**Issue by britneymorgan** [fvcproductions/diversify-me#1]
[ACT-W National Conference](http://www.act-w.org/)

**Comment by FrancesCoronel** [comment]
Hey @britneymorgan - thanks so much for the suggestion but when I looked through their website, I didn't see any link that would allow someone to apply for a grant or scholarship in order to attend the event. 

I'm not including events that allow you to volunteer in exchange for a ticket which seems to be the only way to attend the ACT-W conference without spending any money. 

Thank you again for the suggestion though and please feel free to open another PR with other suggestions.
