### ISSUE TITLE
Add GoCon Canada 2020

### ISSUE THREAD

**Issue by jessicaxiejw** [fvcproductions/diversify-me#13]
Could you add GoCon Canada's Diversity Scholarship?

https://gocon.ca/#diversity-scholarship

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to see if the issue has already been discussed before 🤔️
- [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by Marwan01** [comment]
Hello. I made a PR to add KubeCon, and noticed your raised issue. I added GoCon conference with the link you sent to the Canada section and included it in my PR: https://github.com/fvcproductions/diversify-me/pull/14 If you do not mind. 
I also added your name and Github link to the credits section since creating an issue is also contributing. Hope this PR gets reviewed and approved soon!

**Comment by FrancesCoronel** [comment]
Added in!
